# Generated by Django 4.0.3 on 2022-03-22 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habittracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='daily_goal',
            new_name='overall_goal',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='date_accomplished',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='goal_accomplished',
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_accomplished', models.BooleanField(default=False)),
                ('date_accomplished', models.DateTimeField(auto_now_add=True)),
                ('daily_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_record', to='habittracker.habit')),
            ],
        ),
    ]
