# Generated by Django 4.0.3 on 2022-03-30 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habittracker', '0008_remove_result_goal_accomplished_habit_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='overall_goal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='result',
            name='habit_practiced',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='habittracker.habit'),
        ),
    ]
